language: java
dist: trusty
jdk:
  - oraclejdk8
  #- oraclejdk7
  #- openjdk7

before_install:
    - echo "BEFORE INSTALL"

install:
    - mvn clean install -DskipTests

before_script:
    - echo "MAVEN_OPTS='-Xmx1024m -XX:MaxPermSize=256m'" > ~/.mavenrc

script:
    - mvn test -B
    
after_script:
    - echo "AFTER SCRIPT"

after_success:
  - mvn clean cobertura:cobertura coveralls:report
